"""add height to sections

Revision ID: eadecf5e20c1
Revises: c9f2ca6dd035
Create Date: 2026-04-30 18:42:45.117359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eadecf5e20c1'
down_revision: Union[str, None] = 'c9f2ca6dd035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('height', sa.Integer(), nullable=False, server_default='320'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'height')
    # ### end Alembic commands ###
